### ISSUE TITLE
Text color in Jaxon Footer should be defined with inverted text color

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/jaxon#16]
When switching to a light style variation I encountered an issue with the footer text, as it inherits the color of the body text.

It shows like this:
![Screenshot 2023-04-20 at 6 40 21 PM](https://user-images.githubusercontent.com/4193672/233417789-f050200a-7206-4be8-8355-5bb42f682a37.png)

I think this can be fixed by defining the inverted text color to the text of the footer.

![Screenshot 2023-04-20 at 6 41 00 PM](https://user-images.githubusercontent.com/4193672/233418082-9c250d8c-2e8a-43fa-a7fb-9b5e96a717c2.png)

We'll just need to make this change and update the footer template part.

@mghenciu can you confirm this?

**Comment by mghenciu** [comment]
Thank you for reporting this, I've also noticed the issue yesterday.
Should be fixed with this PR >> https://github.com/Codeinwp/jaxon/pull/17
